### ISSUE TITLE
Epitope Classification

### ISSUE THREAD

**Issue by anar-rzayev** [nicwulab/SARS-CoV-2_Abs#1]
According to the README.md file, it was mentioned for the DL-based antigen identification model, we could have a look at the Epitope_classification.ipynb in CoV_Encoder for more detailed code analysis. However, the link refers to a non-existing page on GitHub. Could you please either update README.md or add the Epitope_classification.ipynb for the CoV_Encoder?

**Comment by wchnicholas** [comment]
Thanks for pointing this out and we apologize for the inconvenience. We totally forgot to update the README when we were revising the manuscript. During first submission, we only have the model for classifying Spike antibodies vs HA antibodies. However, a reviewer asked if we can also do 1) RBD vs NTD vs S2 and 2) RBD vs HA. So the published version of the manuscript ended up having three different classifiers. The README is now updated accordingly. The links to the three classifiers should work now.

**Comment by anar-rzayev** [comment]
Thank you very much Nicholas for fast response and edit of README.md, appreciate it a lot!
It has now become more clear about the Epitope Classification part. One more thing I wanted to elaborate is in RBD_S2_NTD_VH.ipynb, there is so called "RBD-S2-NTD_full_CDR.xlsx" dataset that is loaded and analysed which Ab sequences would bind to specific region of Spike Proteins. However, after searching in whole repository, I could not find such statistics. Could you please elaborate more on this issue?

**Comment by Wangyiquan95** [comment]
Hi, thanks for pointing this out. I just updated data/RBD-S2-NTD_full_CDR.xlsx

**Comment by anar-rzayev** [comment]
Thank you very much again for your updates! It helped a lot!

**Comment by anar-rzayev** [comment]
Thank you very much again for your updates! It helped a lot!
